// src简书/components/Add.vue
<template>
  <div class="add">
    请输入内容：
    <el-input v-model="input" placeholder="请输入内容"></el-input>
    <el-button type="primary" plain @click="add()">提交添加</el-button>
  </div>
</template>

<script>
export default {
  data() {
    return {
      input: ""
    };
  },
  methods: {
    add() {
      if (this.input.length) {
        this.$axios
          .post("http://127.0.0.1:3003/mylist", {
            title: this.input
          })
          .then(res => {
            if (res.status == 201) {
              this.$router.push("/");
            }
          });
      }
    }
  }
};
</script>

<style scoped>
.add {
  text-align: left;
}
.el-input {
  width: 300px;
}
</style>

// 作业/src-react/components/Add.js
import React from 'react';
import './state.css'
import { Input } from 'antd'
import { Button } from 'antd'
import './add.css'

class add extends React.Component {
  constructor() {
    super()
    this.state = {
      num: '',
      title: ''
    }
  }
  enterLoading = () => {
    this.fn();
  };
  fn() {
    this.$axios.post('http://127.0.0.1:3001/mylist', {
      title: this.state.title
    }).then(res => {
      if (res.status == '201') {
        this.props.history.push('/list')
      }
    })
  }
  change(e) {
    this.setState({
      title: e.target.value
    })
  }
  enterIconLoading = () => {
    this.setState({ iconLoading: true });
    setTimeout(() => {
      this.setState({ iconLoading: false });
    }, 1000);
  };
  render() {
    return (
      <div className="add">
        请输入内容：<Input placeholder="请输入内容" value={this.state.title} onChange={(e) => { this.change(e) }} />
        <Button type="primary" loading={this.state.loading} onClick={this.enterLoading}>
          提交
        </Button>
      </div>
    )
  }
}

export default add;
