// 作业/src-vue/components/Details.vue
<template>
  <div class="details">{{input}}</div>
</template>

<script>
export default {
  data() {
    return {
      input: ""
    };
  },
  created() {
    console.log(this.$route.params);
    this.$axios
      .get("http://127.0.0.1:3003/mylist/" + this.$route.params.id)
      .then(res => {
        if (res.status == 200) {
          this.input = res.data.title;
        }
      });
  }
};
</script>

<style scoped>
.details {
  text-align: left;
}
</style>

// 作业/src-react/components/Details.js
import React from 'react';
import './state.css'

class Details extends React.Component {
  constructor() {
    super()
    this.state = {
      num: '',
      obj: {}
    }
  }
  componentDidMount() {
    this.setState({
      num: this.props.match.params.id
    })
    this.$axios('http://127.0.0.1:3001/mylist').then(res => {
      this.setState({
        obj: res.data.find(item => {
          return item.id == this.state.num
        })
      })
    })
  }
  render() {
    return (
      <div className="details">
        {this.state.obj.title}
      </div>
    )
  }
}

export default Details;
